# nodeSelector: {}
# tolerations: {}
# securityContext: {}

zeimage:
  repository: robotinfra/minio-resources-operator
  tag: v0.3.7
  pullPolicy: IfNotPresent
  pullSecrets: []

replicas: 1

# fullnameOverride:
# nameOverride:
serviceAccount:
  create: true
  name: ""

rbac:
  create: true
  apiVersion: v1

serviceMonitor:
  enabled: false
  # labels:
  # namespace:
  # interval:

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 0.01
    memory: 192Mi

livenessProbe:
  enabled: true
  initialDelaySeconds: 2
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  enabled: true
  initialDelaySeconds: 2
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3
